# Generated by Django 4.2.29 on 2026-03-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpuserver',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='别名'),
        ),
    ]
