# Generated by Django 4.2.29 on 2026-03-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu_info', '0002_gpuserver_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpuinfo',
            name='free_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='空闲开始时间'),
        ),
    ]
