# Generated by Django 4.2.29 on 2026-03-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu_info', '0003_gpuinfo_free_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpuinfo',
            name='busy_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='占用开始时间'),
        ),
    ]
