# Generated by Django 4.2.29 on 2026-03-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gputask',
            name='idle_delay_minutes',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, '不延迟'),
                    (1, '空闲超过1分钟'),
                    (3, '空闲超过3分钟'),
                    (5, '空闲超过5分钟'),
                    (10, '空闲超过10分钟'),
                    (30, '空闲超过30分钟'),
                ],
                default=0,
                verbose_name='空闲等待时间',
            ),
        ),
    ]
