# Generated by Django 4.2.29 on 2026-04-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_gputask_idle_delay_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gputaskrunninglog',
            name='stop_requested',
            field=models.BooleanField(default=False, verbose_name='已请求停止'),
        ),
    ]
